-- Core tables used by the Tailrly application.

create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint measurements_data_is_object
    check (jsonb_typeof(data) = 'object')
);

create index if not exists measurements_user_id_idx
  on public.measurements (user_id);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  garment_type text not null,
  notes text,
  budget text,
  created_at timestamptz not null default now(),
  constraint requests_garment_type_not_blank
    check (btrim(garment_type) <> '')
);

create index if not exists requests_user_id_idx
  on public.requests (user_id);

alter table public.measurements enable row level security;
alter table public.requests enable row level security;

create policy "Users can read their own measurements"
  on public.measurements
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own measurements"
  on public.measurements
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own measurements"
  on public.measurements
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own measurements"
  on public.measurements
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their own requests"
  on public.requests
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own requests"
  on public.requests
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own requests"
  on public.requests
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own requests"
  on public.requests
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
